In [1]:
import pandas as pd
import numpy as np
import pickle as pk
from ete3 import Tree

In [2]:
file_name = "/workspaces/CellTreeBench/data/raw/celegans_packer/celegans_1.nwk"
ref_lineage_tree= Tree(file_name, format=1)
print(ref_lineage_tree.get_ascii(show_internal=True))

                                                             /-ABALAAAALAL
                                                   /ABALAAAALA
                                                  |          \-ABALAAAALAR
                                          /ABALAAAAL
                                         |        |          /-ABALAAAALPA
                                         |         \ABALAAAALP
                                         |                   \-ABALAAAALPP
                                  /ABALAAAA
                                 |       |                   /-ABALAAAARLA
                                 |       |         /ABALAAAARL
                                 |       |        |          \-ABALAAAARLP
                                 |        \ABALAAAAR
                                 |                |          /-ABALAAAARRA
                                 |                 \ABALAAAARR
                                 |                           \-ABALAAAARRP
                           /ABALAAA
                          |      |                           /-ABALAAAPALL
                          |      |                 /ABALAAAPAL
                          |      |                |          \-ABALAAAPALR
                          |      |        /ABALAAAPA
                          |      |       |        |          /-ABALAAAPARL
                          |      |       |         \ABALAAAPAR
                          |      |       |                   \-ABALAAAPARR
                          |       \ABALAAAP
                          |              |                   /-ABALAAAPPLL
                          |              |         /ABALAAAPPL
                          |              |        |          \-ABALAAAPPLR
                          |               \ABALAAAPP
                          |                       |          /-ABALAAAPPRL
                     /ABALAA                       \ABALAAAPPR
                    |     |                                  \-ABALAAAPPRR
                    |     |
                    |     |                                  /-ABALAAPAAAL
                    |     |                        /ABALAAPAAA
                    |     |                       |          \-ABALAAPAAAR
                    |     |               /ABALAAPAA
                    |     |              |        |          /-ABALAAPAAPA
                    |     |              |         \ABALAAPAAP
                    |     |       /ABALAAPA                  \-ABALAAPAAPP
                    |     |      |       |
                    |     |      |       |         /-ABALAAPAPA
                    |     |      |        \ABALAAPAP
                    |     |      |                |          /-ABALAAPAPPA
                    |     |      |                 \ABALAAPAPP
                    |      \ABALAAP                          \-ABALAAPAPPP
                    |            |
                    |            |                 /-ABALAAPPAA
                    |            |        /ABALAAPPA
                    |            |       |        |          /-ABALAAPPAPA
                    |            |       |         \ABALAAPPAP
                    |            |       |                   \-ABALAAPPAPP
                    |             \ABALAAPP
                    |                    |                   /-ABALAAPPPAA
                    |                    |         /ABALAAPPPA
                    |                    |        |          \-ABALAAPPPAP
                    |                     \ABALAAPPP
                    |                             |                     /-ABALAAPPPPAA
                    |                             |          /ABALAAPPPPA
                    |                              \ABALAAPPPP          \-ABALAAPPPPAP
                    |                                       |
                    |                                        \-ABALAAPPPPP
                /ABALA
               |    |                                        /-ABALAPAAAAA
               |    |                              /ABALAPAAAA
               |    |                             |          \-ABALAPAAAAP
               |    |                     /ABALAPAAA
               |    |                    |        |          /-ABALAPAAAPA
               |    |                    |         \ABALAPAAAP
               |    |                    |                   \-ABALAPAAAPP
               |    |             /ABALAPAA
               |    |            |       |                   /-ABALAPAAPAA
               |    |            |       |         /ABALAPAAPA
               |    |            |       |        |          \-ABALAPAAPAP
               |    |            |        \ABALAPAAP
               |    |            |                |                     /-ABALAPAAPPAA
               |    |            |                |          /ABALAPAAPPA
               |    |            |                 \ABALAPAAPP          \-ABALAPAAPPAP
               |    |            |                          |
               |    |      /ABALAPA                          \-ABALAPAAPPP
               |    |     |      |
               |    |     |      |                 /-ABALAPAPAA
               |    |     |      |                |
               |    |     |      |        /ABALAPAPA                    /-ABALAPAPAPAA
               |    |     |      |       |        |          /ABALAPAPAPA
               |    |     |      |       |         \ABALAPAPAP          \-ABALAPAPAPAP
               |    |     |      |       |                  |
               |    |     |      |       |                   \-ABALAPAPAPP
               |    |     |       \ABALAPAP
               |    |     |              |                              /-ABALAPAPPAAA
               |    |     |              |                   /ABALAPAPPAA
               |    |     |              |         /ABALAPAPPA          \-ABALAPAPPAAP
               |    |     |              |        |         |
               |    |     |               \ABALAPAPP         \-ABALAPAPPAP
               |    |     |                       |
               |     \ABALAP                      |          /-ABALAPAPPPA
               |          |                        \ABALAPAPPP
               |          |                                  \-ABALAPAPPPP
               |          |
               |          |                        /-ABALAPPAAA
               |          |               /ABALAPPAA
               |          |              |        |          /-ABALAPPAAPA
               |          |              |         \ABALAPPAAP
               |          |              |                   \-ABALAPPAAPP
               |          |       /ABALAPPA
               |          |      |       |                   /-ABALAPPAPAA
               |          |      |       |         /ABALAPPAPA
               |          |      |       |        |          \-ABALAPPAPAP
               |          |      |        \ABALAPPAP
               |          |      |                |          /-ABALAPPAPPA
               |          |      |                 \ABALAPPAPP
               |          |      |                           \-ABALAPPAPPP
               |           \ABALAPP
               |                 |                           /-ABALAPPPAAA
               |                 |                 /ABALAPPPAA
               |                 |                |          \-ABALAPPPAAP
               |                 |        /ABALAPPPA
               |                 |       |        |                     /-ABALAPPPAPAA
               |                 |       |        |          /ABALAPPPAPA
               |                 |       |         \ABALAPPPAP          \-ABALAPPPAPAP
               |                 |       |                  |
               |                  \ABALAPPP                  \-ABALAPPPAPP
               |                         |
               |                         |                              /-ABALAPPPPAAA
               |                         |                   /ABALAPPPPAA
               |                         |         /ABALAPPPPA          \-ABALAPPPPAAP
               |                         |        |         |
               |                          \ABALAPPPP         \-ABALAPPPPAP
               |                                  |
            /ABAL                                 |          /-ABALAPPPPPA
           |   |                                   \ABALAPPPPP
           |   |                                             \-ABALAPPPPPP
           |   |
           |   |                                             /-ABALPAAAAAA
           |   |                                   /ABALPAAAAA
           |   |                                  |          \-ABALPAAAAAP
           |   |                          /ABALPAAAA
           |   |                         |        |          /-ABALPAAAAPA
           |   |                         |         \ABALPAAAAP
           |   |                         |                   \-ABALPAAAAPP
           |   |                  /ABALPAAA
           |   |                 |       |                   /-ABALPAAAPAA
           |   |                 |       |         /ABALPAAAPA
           |   |                 |       |        |          \-ABALPAAAPAP
           |   |                 |        \ABALPAAAP
           |   |                 |                |          /-ABALPAAAPPA
           |   |                 |                 \ABALPAAAPP
           |   |                 |                           \-ABALPAAAPPP
           |   |           /ABALPAA
           |   |          |      |                           /-ABALPAAPAAA
           |   |          |      |                 /ABALPAAPAA
           |   |          |      |                |          \-ABALPAAPAAP
           |   |          |      |        /ABALPAAPA
           |   |          |      |       |        |          /-ABALPAAPAPA
           |   |          |      |       |         \ABALPAAPAP
           |   |          |      |       |                   \-ABALPAAPAPP
           |   |          |       \ABALPAAP
           |   |          |              |                   /-ABALPAAPPAA
           |   |          |              |         /ABALPAAPPA
           |   |          |              |        |          \-ABALPAAPPAP
           |   |          |               \ABALPAAPP
           |   |          |                       |          /-ABALPAAPPPA
           |   |          |                        \ABALPAAPPP
           |   |          |                                  \-ABALPAAPPPP
           |   |     /ABALPA
           |   |    |     |                                  /-ABALPAPAAAA
           |   |    |     |                        /ABALPAPAAA
           |   |    |     |                       |          \-ABALPAPAAAP
           |   |    |     |               /ABALPAPAA
           |   |    |     |              |        |          /-ABALPAPAAPA
           |   |    |     |              |         \ABALPAPAAP
           |   |    |     |              |                   \-ABALPAPAAPP
           |   |    |     |       /ABALPAPA
           |   |    |     |      |       |                   /-ABALPAPAPAA
           |   |    |     |      |       |         /ABALPAPAPA
           |   |    |     |      |       |        |         |           /-ABALPAPAPAPA
           |   |    |     |      |       |        |          \ABALPAPAPAP
           |   |    |     |      |        \ABALPAPAP                    \-ABALPAPAPAPP
           |   |    |     |      |                |
           |   |    |     |      |                |          /-ABALPAPAPPA
           |   |    |     |      |                 \ABALPAPAPP
           |   |    |      \ABALPAP                          \-ABALPAPAPPP
           |   |    |            |
           |   |    |            |                           /-ABALPAPPAAA
           |   |    |            |                 /ABALPAPPAA
           |   |    |            |                |         |           /-ABALPAPPAAPA
           |   |    |            |                |          \ABALPAPPAAP
           |   |    |            |        /ABALPAPPA                    \-ABALPAPPAAPP
           |   |    |            |       |        |
           |   |    |            |       |        |          /-ABALPAPPAPA
           |   |    |            |       |         \ABALPAPPAP
           |   |    |             \ABALPAPP                  \-ABALPAPPAPP
           |   |    |                    |
           |   |    |                    |                   /-ABALPAPPPAA
           |   |    |                    |         /ABALPAPPPA
           |   |    |                    |        |          \-ABALPAPPPAP
           |    \ABALP                    \ABALPAPPP
           |        |                             |          /-ABALPAPPPPA
           |        |                              \ABALPAPPPP
           |        |                                        \-ABALPAPPPPP
           |        |
           |        |                              /-ABALPPAAAA
           |        |                     /ABALPPAAA
           |        |                    |        |          /-ABALPPAAAPA
           |        |                    |         \ABALPPAAAP
           |        |             /ABALPPAA                  \-ABALPPAAAPP
           |        |            |       |
           |        |            |       |         /-ABALPPAAPA
           |        |            |        \ABALPPAAP
           |        |            |                |          /-ABALPPAAPPA
           |        |            |                 \ABALPPAAPP
           |        |            |                           \-ABALPPAAPPP
           |        |      /ABALPPA
           |        |     |      |                           /-ABALPPAPAAA
           |        |     |      |                 /ABALPPAPAA
           |        |     |      |                |          \-ABALPPAPAAP
           |        |     |      |        /ABALPPAPA
           |        |     |      |       |        |          /-ABALPPAPAPA
           |        |     |      |       |         \ABALPPAPAP
           |        |     |      |       |                   \-ABALPPAPAPP
           |        |     |       \ABALPPAP
           |        |     |              |                   /-ABALPPAPPAA
           |        |     |              |         /ABALPPAPPA
           |        |     |              |        |          \-ABALPPAPPAP
           |        |     |               \ABALPPAPP
           |        |     |                       |                     /-ABALPPAPPPAA
           |        |     |                       |          /ABALPPAPPPA
           |        |     |                        \ABALPPAPPP          \-ABALPPAPPPAP
           |        |     |                                 |
           |         \ABALPP                                 \-ABALPPAPPPP
           |              |
           |              |                                  /-ABALPPPAAAA
           |              |                        /ABALPPPAAA
           |              |                       |          \-ABALPPPAAAP
           |              |               /ABALPPPAA
           |              |              |        |          /-ABALPPPAAPD
           |              |              |         \ABALPPPAAP
           |              |              |                   \-ABALPPPAAPV
           |              |       /ABALPPPA
           |              |      |       |                   /-ABALPPPAPAD
           |              |      |       |         /ABALPPPAPA
           |              |      |       |        |          \-ABALPPPAPAV
           |              |      |        \ABALPPPAP
           |              |      |                |          /-ABALPPPAPPA
           |              |      |                 \ABALPPPAPP
           |              |      |                          |           /-ABALPPPAPPPA
           |              |      |                           \ABALPPPAPPP
           |               \ABALPPP                                     \-ABALPPPAPPPP
           |                     |
           |                     |                           /-ABALPPPPAAD
           |                     |                 /ABALPPPPAA
           |                     |                |          \-ABALPPPPAAV
           |                     |        /ABALPPPPA
           |                     |       |        |                     /-ABALPPPPAPAA
           |                     |       |        |          /ABALPPPPAPA
           |                     |       |         \ABALPPPPAP          \-ABALPPPPAPAP
           |                     |       |                  |
           |                      \ABALPPPP                  \-ABALPPPPAPP
           |                             |
           |                             |                   /-ABALPPPPPAA
         /ABA                            |         /ABALPPPPPA
        |  |                             |        |          \-ABALPPPPPAP
        |  |                             |        |
        |  |                              \ABALPPPPP                    /-ABALPPPPPPAA
        |  |                                      |          /ABALPPPPPPA
        |  |                                      |         |           \-ABALPPPPPPAP
        |  |                                       \ABALPPPPPP
        |  |                                                |           /-ABALPPPPPPPA
        |  |                                                 \ABALPPPPPPP
        |  |                                                            \-ABALPPPPPPPP
        |  |
        |  |                                                 /-ABARAAAAAAA
        |  |                                       /ABARAAAAAA
        |  |                                      |          \-ABARAAAAAAP
        |  |                              /ABARAAAAA
        |  |                             |        |          /-ABARAAAAAPA
        |  |                             |         \ABARAAAAAP
        |  |                      /ABARAAAA                  \-ABARAAAAAPP
        |  |                     |       |
        |  |                     |       |                   /-ABARAAAAPAA
        |  |                     |       |         /ABARAAAAPA
        |  |                     |        \ABARAAAAP         \-ABARAAAAPAP
        |  |                     |                |
        |  |                     |                 \-ABARAAAAPP
        |  |               /ABARAAA
        |  |              |      |                           /-ABARAAAPAAA
        |  |              |      |                 /ABARAAAPAA
        |  |              |      |                |          \-ABARAAAPAAP
        |  |              |      |        /ABARAAAPA
        |  |              |      |       |        |          /-ABARAAAPAPA
        |  |              |      |       |         \ABARAAAPAP
        |  |              |      |       |                   \-ABARAAAPAPP
        |  |              |       \ABARAAAP
        |  |              |              |                   /-ABARAAAPPAA
        |  |              |              |         /ABARAAAPPA
        |  |              |              |        |          \-ABARAAAPPAP
        |  |              |               \ABARAAAPP
        |  |              |                       |          /-ABARAAAPPPA
        |  |              |                        \ABARAAAPPP
        |  |              |                                  \-ABARAAAPPPP
        |  |         /ABARAA
        |  |        |     |                                  /-ABARAAPAAAA
        |  |        |     |                        /ABARAAPAAA
        |  |        |     |                       |          \-ABARAAPAAAP

In [3]:
# count the number of leaves in the tree
n_leaves = ref_lineage_tree.get_leaf_names()
print("Number of leaves: ", len(n_leaves))

Number of leaves:  668

In [57]:
cell_meta = pd.read_csv('/workspaces/1-phydist/main/phylodist/notebooks/17-celegans_large/raw/coldata_df.csv', index_col=0, low_memory=False)
cell_meta

,barcode,Size_Factor,n.umi,cell,sample.name,batch,time.point,species,suffix,sample,...,cbr_lineage_specific,cel_lineage_broad,cbr_lineage_broad,lineage_broad,lineage_specific,cel_lineage_complete,cbr_lineage_complete,lineage_complete,germline_pseudotime,global_local_cluster
AAACCTGAGACAATAC-300.1.1,AAACCTGAGACAATAC-300.1.1,1.109700,1618,AAACCTGAGACAATAC-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,unassigned,unassigned,unassigned,unassigned,MSxpappp,unassigned,MSxpappp,NaN,20_5
AAACCTGAGGGCTCTC-300.1.1,AAACCTGAGGGCTCTC-300.1.1,1.578607,2305,AAACCTGAGGGCTCTC-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,MSxapaap,unassigned,MSxapaap,MSxapaap,MSxapaap,unassigned,MSxapaap,NaN,99_98
AAACCTGAGTGCGTGA-300.1.1,AAACCTGAGTGCGTGA-300.1.1,2.536359,3687,AAACCTGAGTGCGTGA-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,NaN,3_47
AAACCTGAGTTGAGTA-300.1.1,AAACCTGAGTTGAGTA-300.1.1,2.915885,4238,AAACCTGAGTTGAGTA-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,Dxxp,unassigned,Dxxp,Dxap,Dxap,unassigned,Dxap,NaN,2_25
AAACCTGCAAGACGTG-300.1.1,AAACCTGCAAGACGTG-300.1.1,0.690984,997,AAACCTGCAAGACGTG-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,NaN,115_42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTCATCCAATGGT-500.3,TTTGTCATCCAATGGT-500.3,1.304276,1901,TTTGTCATCCAATGGT-500.3,181030_Cb_EMB_500_3,500_min_batch_1,500_minutes,C.briggsae,500.3,20,...,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,NaN,26_29
TTTGTCATCGTAGGAG-500.3,TTTGTCATCGTAGGAG-500.3,0.939876,1355,TTTGTCATCGTAGGAG-500.3,181030_Cb_EMB_500_3,500_min_batch_1,500_minutes,C.briggsae,500.3,20,...,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,NaN,81_26
TTTGTCATCGTTTATC-500.3,TTTGTCATCGTTTATC-500.3,0.585790,858,TTTGTCATCGTTTATC-500.3,181030_Cb_EMB_500_3,500_min_batch_1,500_minutes,C.briggsae,500.3,20,...,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,NaN,17_66
TTTGTCATCTGCGACG-500.3,TTTGTCATCTGCGACG-500.3,0.503972,735,TTTGTCATCTGCGACG-500.3,181030_Cb_EMB_500_3,500_min_batch_1,500_minutes,C.briggsae,500.3,20,...,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,unassigned,NaN,114_25
TTTGTCATCTTAGCCC-500.3,TTTGTCATCTTAGCCC-500.3,0.961190,1395,TTTGTCATCTTAGCCC-500.3,181030_Cb_EMB_500_3,500_min_batch_1,500_minutes,C.briggsae,500.3,20,...,ABpxpaapaa,unassigned,ABpxpaapaa,ABpxpaapaa,ABpxpaapaa,unassigned,ABpxpaapaa,ABpxpaapaa,NaN,51_50

In [58]:
cell_meta.keys()

Index(['barcode', 'Size_Factor', 'n.umi', 'cell', 'sample.name', 'batch',
       'time.point', 'species', 'suffix', 'sample', 'ws260_n.umi',
       'ws260_Size_Factor', 'cell.type', 'cell.subtype', 'plot.cell.type',
       'raw.embryo.time', 'embryo.time', 'lineage_packer', 'genotype',
       'assigned_cell_type', 'to.filter', 'cluster.cell.type',
       'cell.subtype.2', 'cluster', 'umi.quant', 'umap_1', 'umap_2',
       'cell.class', 'joint.cell.subtype', 'round.2.doublets', 'tissue.type',
       'mt.frac', 'round.1.cell.type', 'plot.ct', 'n.r1ct.scores.past.thresh',
       'initial.cluster', 'max.score', 'br.cell.subtype', 'to.filter2',
       'cell.old.name', 'to.filter.bkgd', 'br.broad.cell.type',
       'cluster_seurat', 'jt_cell_class', 'smoothed.embryo.time',
       'embryo.time.bin', 'jt.cell.class.time.bin', 'jt.cell.subtype2',
       'old_cds_barcodes', 'manual_lineage', 'lineage_auto_briggsae',
       'manual_lineage2', 'db.version', 'batch4', 'batch3', 'batch_300',
       'batch_400', 'batch_500', 'batch_120', 'batch_180', 'batch_240',
       'batch_360', 'cell_short', 'source', 'ws260_cell', 'global_cluster',
       'supp.cell.type', 'supp.cell.type2', 'supp.cell.type3',
       'est.bg.prop.mus', 'est.bg.prop.hyp', 'est.bg.prop.both', 'est.bg.prop',
       'dataset', 'dataset2', 'dataset3', 'cell_type', 'filter',
       'cel_lineage_specific', 'cbr_lineage_specific', 'cel_lineage_broad',
       'cbr_lineage_broad', 'lineage_broad', 'lineage_specific',
       'cel_lineage_complete', 'cbr_lineage_complete', 'lineage_complete',
       'germline_pseudotime', 'global_local_cluster'],
      dtype='object')

In [59]:
cell_meta['species'].unique()

array(['C.elegans', 'C.briggsae'], dtype=object)

In [60]:
print(len(cell_meta))
pruned_meta = cell_meta[~cell_meta['lineage_broad'].isna()]
# exclude rows with lineage_broad == 'unassigned'
pruned_meta = pruned_meta[pruned_meta['lineage_broad'] != 'unassigned']
print(f"# of C.elegans: {len(pruned_meta[pruned_meta['species'] == 'C.elegans'])}")
print(f"# of C.briggsae: {len(pruned_meta[pruned_meta['species'] == 'C.briggsae'])}")
pruned_meta

389755
# of C.elegans: 25383
# of C.briggsae: 56569

,barcode,Size_Factor,n.umi,cell,sample.name,batch,time.point,species,suffix,sample,...,cbr_lineage_specific,cel_lineage_broad,cbr_lineage_broad,lineage_broad,lineage_specific,cel_lineage_complete,cbr_lineage_complete,lineage_complete,germline_pseudotime,global_local_cluster
AAACCTGAGGGCTCTC-300.1.1,AAACCTGAGGGCTCTC-300.1.1,1.578607,2305,AAACCTGAGGGCTCTC-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,MSxapaap,unassigned,MSxapaap,MSxapaap,MSxapaap,unassigned,MSxapaap,NaN,99_98
AAACCTGAGTTGAGTA-300.1.1,AAACCTGAGTTGAGTA-300.1.1,2.915885,4238,AAACCTGAGTTGAGTA-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,Dxxp,unassigned,Dxxp,Dxap,Dxap,unassigned,Dxap,NaN,2_25
AAACCTGCAAGGTTCT-300.1.1,AAACCTGCAAGGTTCT-300.1.1,0.907561,1324,AAACCTGCAAGGTTCT-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,ABalpappaa/ABarapapaa,unassigned,ABalpappaa/ABarapapaa,ABalpappaa/ABarapapaa,ABalpappaa/ABarapapaa,unassigned,ABalpappaa/ABarapapaa,NaN,72_4
AAACCTGGTGTGAATA-300.1.1,AAACCTGGTGTGAATA-300.1.1,0.988692,1442,AAACCTGGTGTGAATA-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,ABalppppa/ABpraaapa,unassigned,ABalppppa/ABpraaapa,ABalppppa/ABpraaapa,ABalppppa/ABpraaapa,unassigned,ABalppppa/ABpraaapa,NaN,18_17
AAACCTGGTTTACTCT-300.1.1,AAACCTGGTTTACTCT-300.1.1,0.880747,1281,AAACCTGGTTTACTCT-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,ABaraaaapa,unassigned,ABaraaaapa,ABaraaaapa,ABaraaaapa,unassigned,ABaraaaapa,NaN,40_39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTCCTCTCATTGCGA-500.3,TTTCCTCTCATTGCGA-500.3,0.948127,1382,TTTCCTCTCATTGCGA-500.3,181030_Cb_EMB_500_3,500_min_batch_1,500_minutes,C.briggsae,500.3,20,...,ABalapaaaa/ABalappapa,unassigned,ABalapaaaa/ABalappapa,ABalapaaaa/ABalappapa,ABalapaaaa/ABalappapa,unassigned,ABalapaaaa/ABalappapa,ABalapaaaa/ABalappapa,NaN,85_9
TTTCCTCTCGGTGTCG-500.3,TTTCCTCTCGGTGTCG-500.3,0.410465,596,TTTCCTCTCGGTGTCG-500.3,181030_Cb_EMB_500_3,500_min_batch_1,500_minutes,C.briggsae,500.3,20,...,MSpaapaa,unassigned,MSpaapaa,MSpaapaa,MSpaapaa,unassigned,MSpaapaa,MSpaapaa,NaN,14_54
TTTCCTCTCTAACTTC-500.3,TTTCCTCTCTAACTTC-500.3,0.874559,1272,TTTCCTCTCTAACTTC-500.3,181030_Cb_EMB_500_3,500_min_batch_1,500_minutes,C.briggsae,500.3,20,...,ABalapppaa,unassigned,ABalapppaa,ABalapppaa,ABalapppaa,unassigned,ABalapppaa,ABalapppaa,NaN,75_20
TTTGCGCGTGACTCAT-500.3,TTTGCGCGTGACTCAT-500.3,0.441405,640,TTTGCGCGTGACTCAT-500.3,181030_Cb_EMB_500_3,500_min_batch_1,500_minutes,C.briggsae,500.3,20,...,ABarpaaaap/ABarpaaapa,unassigned,ABarpaaaap/ABarpaaapa,ABarpaaaap/ABarpaaapa,ABarpaaaap/ABarpaaapa,unassigned,ABarpaaaap/ABarpaaapa,ABarpaaaap/ABarpaaapa,NaN,31_12
TTTGTCATCTTAGCCC-500.3,TTTGTCATCTTAGCCC-500.3,0.961190,1395,TTTGTCATCTTAGCCC-500.3,181030_Cb_EMB_500_3,500_min_batch_1,500_minutes,C.briggsae,500.3,20,...,ABpxpaapaa,unassigned,ABpxpaapaa,ABpxpaapaa,ABpxpaapaa,unassigned,ABpxpaapaa,ABpxpaapaa,NaN,51_50

In [61]:
the_species = 'C.elegans'
pruned_meta = pruned_meta[pruned_meta['species'] == the_species]
# pruned_meta.to_csv("celegnas_meta.csv")
pruned_meta

,barcode,Size_Factor,n.umi,cell,sample.name,batch,time.point,species,suffix,sample,...,cbr_lineage_specific,cel_lineage_broad,cbr_lineage_broad,lineage_broad,lineage_specific,cel_lineage_complete,cbr_lineage_complete,lineage_complete,germline_pseudotime,global_local_cluster
AAACCTGAGGGCTCTC-300.1.1,AAACCTGAGGGCTCTC-300.1.1,1.578607,2305,AAACCTGAGGGCTCTC-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,MSxapaap,unassigned,MSxapaap,MSxapaap,MSxapaap,unassigned,MSxapaap,NaN,99_98
AAACCTGAGTTGAGTA-300.1.1,AAACCTGAGTTGAGTA-300.1.1,2.915885,4238,AAACCTGAGTTGAGTA-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,Dxxp,unassigned,Dxxp,Dxap,Dxap,unassigned,Dxap,NaN,2_25
AAACCTGCAAGGTTCT-300.1.1,AAACCTGCAAGGTTCT-300.1.1,0.907561,1324,AAACCTGCAAGGTTCT-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,ABalpappaa/ABarapapaa,unassigned,ABalpappaa/ABarapapaa,ABalpappaa/ABarapapaa,ABalpappaa/ABarapapaa,unassigned,ABalpappaa/ABarapapaa,NaN,72_4
AAACCTGGTGTGAATA-300.1.1,AAACCTGGTGTGAATA-300.1.1,0.988692,1442,AAACCTGGTGTGAATA-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,ABalppppa/ABpraaapa,unassigned,ABalppppa/ABpraaapa,ABalppppa/ABpraaapa,ABalppppa/ABpraaapa,unassigned,ABalppppa/ABpraaapa,NaN,18_17
AAACCTGGTTTACTCT-300.1.1,AAACCTGGTTTACTCT-300.1.1,0.880747,1281,AAACCTGGTTTACTCT-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,unassigned,ABaraaaapa,unassigned,ABaraaaapa,ABaraaaapa,ABaraaaapa,unassigned,ABaraaaapa,NaN,40_39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTTCCCTGACT-r17,TTTGGTTTCCCTGACT-r17,1.658362,2394,TTTGGTTTCCCTGACT-r17,Murray_r17,Murray_r17,mixed,C.elegans,r17,38,...,unassigned,ABalapxppa/ABalaapppp/ABalapaapp,unassigned,ABalapxppa/ABalaapppp/ABalapaapp,ABalapxppa,ABalapxppa,unassigned,ABalapxppa,NaN,25_24
TTTGTCACATTAGGCT-r17,TTTGTCACATTAGGCT-r17,1.352404,1945,TTTGTCACATTAGGCT-r17,Murray_r17,Murray_r17,mixed,C.elegans,r17,38,...,unassigned,ABpxpapapa,unassigned,ABpxpapapa,ABpxpapapa,ABpxpapapa,unassigned,ABpxpapapa,NaN,101_19
TTTGTCAGTCGAACAG-r17,TTTGTCAGTCGAACAG-r17,1.857751,2696,TTTGTCAGTCGAACAG-r17,Murray_r17,Murray_r17,mixed,C.elegans,r17,38,...,unassigned,ABpxpaaap,unassigned,ABpxpaaap,ABpxpaaap,ABpxpaaap,unassigned,ABpxpaaap,NaN,66_65
TTTGTCATCACGCATA-r17,TTTGTCATCACGCATA-r17,7.479818,10882,TTTGTCATCACGCATA-r17,Murray_r17,Murray_r17,mixed,C.elegans,r17,38,...,unassigned,ABpxaap,unassigned,ABpxaap,ABpxaap,ABpxaap,unassigned,ABpxaap,NaN,11_10
TTTGTCATCGCCTGAG-r17,TTTGTCATCGCCTGAG-r17,1.974634,2858,TTTGTCATCGCCTGAG-r17,Murray_r17,Murray_r17,mixed,C.elegans,r17,38,...,unassigned,ABpxpaapa,unassigned,ABpxpaapa,ABpxpaapa,ABpxpaapa,unassigned,ABpxpaapa,NaN,18_17

In [62]:
meta_lineages = pruned_meta['lineage_broad'].str.split('/', expand=True)
meta_lineages.index = pruned_meta.index
meta_lineages

                                   0           1           2
AAACCTGAGGGCTCTC-300.1.1    MSxapaap        None        None
AAACCTGAGTTGAGTA-300.1.1        Dxxp        None        None
AAACCTGCAAGGTTCT-300.1.1  ABalpappaa  ABarapapaa        None
AAACCTGGTGTGAATA-300.1.1   ABalppppa   ABpraaapa        None
AAACCTGGTTTACTCT-300.1.1  ABaraaaapa        None        None
...                              ...         ...         ...
TTTGGTTTCCCTGACT-r17      ABalapxppa  ABalaapppp  ABalapaapp
TTTGTCACATTAGGCT-r17      ABpxpapapa        None        None
TTTGTCAGTCGAACAG-r17       ABpxpaaap        None        None
TTTGTCATCACGCATA-r17         ABpxaap        None        None
TTTGTCATCGCCTGAG-r17       ABpxpaapa        None        None

[25383 rows x 3 columns]

In [63]:
lineage_patterns = meta_lineages.values.flatten()
lineage_patterns = lineage_patterns[~(lineage_patterns == None)]
lineage_patterns = np.unique(lineage_patterns)
print(len(lineage_patterns))
lineage_patterns

373

array(['ABalaaaa', 'ABalaaaal', 'ABalaaaala', 'ABalaaaalp', 'ABalaaaar',
       'ABalaaaarx', 'ABalaaap', 'ABalaaapal', 'ABalaaapar', 'ABalaaappl',
       'ABalaaappr', 'ABalaaapx', 'ABalaapa', 'ABalaapaa', 'ABalaapaaa',
       'ABalaapaap', 'ABalaapap', 'ABalaapapp', 'ABalaapp', 'ABalaappa',
       'ABalaappap', 'ABalaappp', 'ABalaapppa', 'ABalaapppp', 'ABalaax',
       'ABalapaa', 'ABalapaaa', 'ABalapaaaa', 'ABalapaaap', 'ABalapaap',
       'ABalapaapa', 'ABalapaapp', 'ABalappa', 'ABalappaa', 'ABalappaap',
       'ABalappap', 'ABalappapa', 'ABalappapp', 'ABalapppaa', 'ABalapx',
       'ABalapxp', 'ABalapxpa', 'ABalapxpap', 'ABalapxpp', 'ABalapxppa',
       'ABalapxppp', 'ABalpaaa', 'ABalpaaaa', 'ABalpaaaaa', 'ABalpaaaap',
       'ABalpaaap', 'ABalpaap', 'ABalpaapa', 'ABalpaapaa', 'ABalpaapap',
       'ABalpaapp', 'ABalpaappa', 'ABalpaappp', 'ABalpapa', 'ABalpapaa',
       'ABalpapaaa', 'ABalpapap', 'ABalpapapa', 'ABalpapp', 'ABalpappa',
       'ABalpappaa', 'ABalpappap', 'ABalpappp', 'ABalpapppa',
       'ABalpapppp', 'ABalpax', 'ABalppa', 'ABalppaa', 'ABalppaaa',
       'ABalppaaap', 'ABalppaap', 'ABalppaapp', 'ABalppap', 'ABalppapa',
       'ABalppapaa', 'ABalppapap', 'ABalppapp', 'ABalppappa',
       'ABalppappp', 'ABalppp', 'ABalpppa', 'ABalpppaa', 'ABalpppaaa',
       'ABalpppaap', 'ABalpppap', 'ABalpppapa', 'ABalpppapp', 'ABalpppp',
       'ABalppppa', 'ABalppppaa', 'ABalppppap', 'ABalppppp', 'ABalpppppa',
       'ABalpppppp', 'ABaraaaa', 'ABaraaaaa', 'ABaraaaaax', 'ABaraaaap',
       'ABaraaaapa', 'ABaraaap', 'ABaraaapa', 'ABaraaapaa', 'ABaraaapap',
       'ABaraaapp', 'ABaraaappa', 'ABaraaappp', 'ABaraapaaa',
       'ABaraappaa', 'ABaraapx', 'ABaraapxa', 'ABaraapxap', 'ABaraapxp',
       'ABaraapxpa', 'ABaraapxpp', 'ABaraax', 'ABarapa', 'ABarapaa',
       'ABarapaaa', 'ABarapaaaa', 'ABarapaaap', 'ABarapaap', 'ABarapap',
       'ABarapapa', 'ABarapapaa', 'ABarapapap', 'ABarapapp', 'ABarapappa',
       'ABarapappp', 'ABarappa', 'ABarappaa', 'ABarappaaa', 'ABarappap',
       'ABarappapa', 'ABarappp', 'ABarapppa', 'ABarapppaa', 'ABarapppap',
       'ABarapppp', 'ABarappppa', 'ABarappppp', 'ABarpaaa', 'ABarpaaaa',
       'ABarpaaaap', 'ABarpaaap', 'ABarpaaapa', 'ABarpaap', 'ABarpaapx',
       'ABarpapa', 'ABarpapaa', 'ABarpapaaa', 'ABarpapaap', 'ABarpapap',
       'ABarpapp', 'ABarpappa', 'ABarpappp', 'ABarpax', 'ABarppx',
       'ABarppxa', 'ABarppxaa', 'ABarppxap', 'ABarppxapp', 'ABarppxp',
       'ABarppxpa', 'ABarppxpp', 'ABarpx', 'ABaxx', 'ABplaaaa',
       'ABplaaaaa', 'ABplaaaaaa', 'ABplaaaaap', 'ABplaaaap', 'ABplaaap',
       'ABplaaapa', 'ABplaaapp', 'ABplpapp', 'ABplpappa', 'ABplpappaa',
       'ABplpappp', 'ABplpapppa', 'ABplpapppp', 'ABpraaa', 'ABpraaaa',
       'ABpraaaaa', 'ABpraaaaaa', 'ABpraaaaap', 'ABpraaaap', 'ABpraaaapa',
       'ABpraaaapp', 'ABpraaap', 'ABpraaapa', 'ABpraaapaa', 'ABpraaapap',
       'ABpraaapp', 'ABpraaappa', 'ABpraaappp', 'ABprpapp', 'ABprpappa',
       'ABprpappaa', 'ABprpappap', 'ABprpappp', 'ABprpapppa',
       'ABprpapppp', 'ABpxaap', 'ABpxaapa', 'ABpxaapaa', 'ABpxaapaaa',
       'ABpxaapaap', 'ABpxaapap', 'ABpxaapapa', 'ABpxaapapp', 'ABpxaapp',
       'ABpxaappa', 'ABpxaappp', 'ABpxapa', 'ABpxapaa', 'ABpxapaaa',
       'ABpxapaaaa', 'ABpxapaaap', 'ABpxapaaapa', 'ABpxapaap', 'ABpxapap',
       'ABpxapapa', 'ABpxapapaa', 'ABpxapapp', 'ABpxapappp', 'ABpxapp',
       'ABpxappa', 'ABpxappaa', 'ABpxappap', 'ABpxappp', 'ABpxapppa',
       'ABpxapppaa', 'ABpxapppap', 'ABpxapppp', 'ABpxax', 'ABpxpa',
       'ABpxpaa', 'ABpxpaaa', 'ABpxpaaaa', 'ABpxpaaaaa', 'ABpxpaaaap',
       'ABpxpaaap', 'ABpxpaaapa', 'ABpxpaaapp', 'ABpxpaap', 'ABpxpaapa',
       'ABpxpaapaa', 'ABpxpaapap', 'ABpxpaapp', 'ABpxpaappa',
       'ABpxpaappp', 'ABpxpap', 'ABpxpapa', 'ABpxpapaa', 'ABpxpapaaa',
       'ABpxpapap', 'ABpxpapapa', 'ABpxpapapp', 'ABpxpp', 'ABpxppa',
       'ABpxppaa', 'ABpxppaaa', 'ABpxppaaaa', 'ABpxppaap', 'ABpxppaapa',
       'ABpxppaapp', 'ABpxppap', 'ABpxppapa', 'ABpxppapaa', 'ABpxppapap',
       'ABpxppapp', 'ABpxppappa', 'ABpxppappp', 'ABpxppp', 'ABpxpppa',
       'ABpxpppaa', 'ABpxpppaaa', 'ABpxpppaap', 'ABpxpppap', 'ABpxpppapa',
       'ABpxpppp', 'ABpxppppa', 'ABpxppppaa', 'ABpxppppap', 'ABpxppppp',
       'ABpxpppppa', 'ABpxpppppp', 'Caapa', 'Cpapa', 'Cx', 'Cxa', 'Cxaa',
       'Cxaax', 'Cxap', 'Cxapp', 'Cxp', 'Cxpa', 'Cxpaa', 'Cxpaaa',
       'Cxpap', 'Cxpapa', 'Cxpapp', 'Cxpp', 'Cxppa', 'Cxppaa', 'Cxppp',
       'Cxpppa', 'Cxpppp', 'Cxpxap', 'Dx', 'Dxx', 'Dxxa', 'Dxxp', 'Exx',
       'Exxx', 'MSaaaaa', 'MSaaaaaa', 'MSaaaaap', 'MSaaaap', 'MSaaaapa',
       'MSaaaapp', 'MSaaapaa', 'MSaaapp', 'MSaappa', 'MSpaaaa',
       'MSpaaaaa', 'MSpaaaap', 'MSpaaap', 'MSpaaapa', 'MSpaaapp',
       'MSpaapaa', 'MSpappa', 'MSx', 'MSxa', 'MSxaa', 'MSxaaa', 'MSxaap',
       'MSxaapa', 'MSxaapap', 'MSxap', 'MSxapa', 'MSxapaa', 'MSxapaaa',
       'MSxapaap', 'MSxapap', 'MSxapapa', 'MSxapapp', 'MSxapp', 'MSxappp',
       'MSxapppa', 'MSxapppp', 'MSxp', 'MSxpa', 'MSxpaa', 'MSxpaaa',
       'MSxpaaaa', 'MSxpaap', 'MSxpap', 'MSxpapa', 'MSxpapaa', 'MSxpapp',
       'MSxpp', 'MSxppa', 'MSxppaa', 'MSxppap', 'MSxppp', 'MSxpppa',
       'MSxpppp'], dtype=object)

In [64]:
from tqdm import tqdm

lineages = pd.Series(lineage_patterns)
regex_lineages = lineages.str.replace('x', '[xaplrvd]')
matches = pd.DataFrame(np.zeros((len(lineages), len(lineages))).astype(bool))
matches.columns = regex_lineages
for rexp in tqdm(regex_lineages):
  matches[rexp] = lineages.str.fullmatch(rexp)
matches.index = lineages
matches

  0%|          | 0/373 [00:00<?, ?it/s]

100%|██████████| 373/373 [00:00<00:00, 3859.11it/s]

,ABalaaaa,ABalaaaal,ABalaaaala,ABalaaaalp,ABalaaaar,ABalaaaar[xaplrvd],ABalaaap,ABalaaapal,ABalaaapar,ABalaaappl,...,MS[xaplrvd]papa,MS[xaplrvd]papaa,MS[xaplrvd]papp,MS[xaplrvd]pp,MS[xaplrvd]ppa,MS[xaplrvd]ppaa,MS[xaplrvd]ppap,MS[xaplrvd]ppp,MS[xaplrvd]pppa,MS[xaplrvd]pppp
ABalaaaa,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABalaaaal,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABalaaaala,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABalaaaalp,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABalaaaar,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSxppaa,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
MSxppap,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
MSxppp,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
MSxpppa,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
MSxpppp,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [65]:
# nothing unmatched
(matches.sum(axis=1) == 0).sum()

0

In [66]:
sorter = np.argsort(- matches.sum(axis=0))
ordered_cols = matches.columns[sorter]
ordered_matches = matches[ordered_cols].iloc[sorter]
match_counts = ordered_matches.sum(axis=0)
match_counts

ABalaaaa              1
ABp[xaplrvd]paapp     1
ABp[xaplrvd]paapap    1
ABp[xaplrvd]paapaa    1
ABp[xaplrvd]paapa     1
                     ..
ABaraa[xaplrvd]       1
ABaraap[xaplrvd]pp    1
ABaraap[xaplrvd]pa    1
ABarapap              1
MS[xaplrvd]pppp       1
Length: 373, dtype: int64

In [67]:
# No multiple matches
# The labels' quality is better than packer's paper. 
multi_match = match_counts[match_counts > 1]
print(len(multi_match))
multi_match

0

Series([], dtype: int64)

In [68]:
# find rows matching just one regex (themself)
good_lineages = np.argwhere((matches.sum(axis=1) == 1).values).flatten()
# remove columns (regex) for bad lineages
unique_matches = matches.iloc[:, good_lineages]
assert (unique_matches.sum(axis=1) == 1).all()

metalineage_to_regex = {}
for lineage in unique_matches.index:
  metalineage_to_regex[lineage] = unique_matches.columns[unique_matches.loc[lineage].argmax()]

meta_regex_lineages = meta_lineages.replace(metalineage_to_regex)
meta_regex_lineages

                                             0           1           2
AAACCTGAGGGCTCTC-300.1.1      MS[xaplrvd]apaap        None        None
AAACCTGAGTTGAGTA-300.1.1  D[xaplrvd][xaplrvd]p        None        None
AAACCTGCAAGGTTCT-300.1.1            ABalpappaa  ABarapapaa        None
AAACCTGGTGTGAATA-300.1.1             ABalppppa   ABpraaapa        None
AAACCTGGTTTACTCT-300.1.1            ABaraaaapa        None        None
...                                        ...         ...         ...
TTTGGTTTCCCTGACT-r17        ABalap[xaplrvd]ppa  ABalaapppp  ABalapaapp
TTTGTCACATTAGGCT-r17        ABp[xaplrvd]papapa        None        None
TTTGTCAGTCGAACAG-r17         ABp[xaplrvd]paaap        None        None
TTTGTCATCACGCATA-r17           ABp[xaplrvd]aap        None        None
TTTGTCATCGCCTGAG-r17         ABp[xaplrvd]paapa        None        None

[25383 rows x 3 columns]

In [69]:
meta_regex_lineages_joined = meta_regex_lineages.apply(
    lambda x: '|'.join(x.dropna().astype(str)),
    axis=1
)
meta_regex_lineages_joined

AAACCTGAGGGCTCTC-300.1.1                            MS[xaplrvd]apaap
AAACCTGAGTTGAGTA-300.1.1                        D[xaplrvd][xaplrvd]p
AAACCTGCAAGGTTCT-300.1.1                       ABalpappaa|ABarapapaa
AAACCTGGTGTGAATA-300.1.1                         ABalppppa|ABpraaapa
AAACCTGGTTTACTCT-300.1.1                                  ABaraaaapa
                                              ...
TTTGGTTTCCCTGACT-r17        ABalap[xaplrvd]ppa|ABalaapppp|ABalapaapp
TTTGTCACATTAGGCT-r17                              ABp[xaplrvd]papapa
TTTGTCAGTCGAACAG-r17                               ABp[xaplrvd]paaap
TTTGTCATCACGCATA-r17                                 ABp[xaplrvd]aap
TTTGTCATCGCCTGAG-r17                               ABp[xaplrvd]paapa
Length: 25383, dtype: object

In [70]:
# If we group lineage patterns by their regex, we get 304 unique group labels
meta_regex_lineages_joined_set = meta_regex_lineages_joined.unique()
meta_regex_lineages_joined_set_to_cell_ids = {}
for reg in meta_regex_lineages_joined_set:
  meta_regex_lineages_joined_set_to_cell_ids[reg] = meta_regex_lineages_joined[meta_regex_lineages_joined == reg].index.values

print(len(meta_regex_lineages_joined_set))

304

In [71]:
meta_regex_lineages_joined_set

array(['MS[xaplrvd]apaap', 'D[xaplrvd][xaplrvd]p',
       'ABalpappaa|ABarapapaa', 'ABalppppa|ABpraaapa', 'ABaraaaapa',
       'ABp[xaplrvd]ppapaa', 'ABalpaapa|ABaraaapa',
       'ABalaaaala|ABalaapaaa', 'ABp[xaplrvd]paaaaa',
       'ABp[xaplrvd]ppppaa', 'ABp[xaplrvd]aapaap', 'ABp[xaplrvd]ppppap',
       'ABarpp[xaplrvd]pa', 'MS[xaplrvd]apaaa', 'ABp[xaplrvd]ppaapa',
       'MS[xaplrvd]apppp', 'ABalppapaa|ABarapppaa',
       'D[xaplrvd][xaplrvd]a', 'ABalaapppa|ABalapaapa',
       'ABp[xaplrvd]appaa', 'ABprpappap', 'ABp[xaplrvd]apaap',
       'ABalaapppp|ABalapaapp', 'ABalapaaap|ABalappapp', 'C[xaplrvd]ppa',
       'ABp[xaplrvd]ppppa', 'ABp[xaplrvd]apaaapa', 'ABalappaap',
       'ABprpapppp', 'Caapa', 'ABalapppaa', 'ABp[xaplrvd]apppap',
       'ABalppapa|ABarapppa', 'ABp[xaplrvd]paappp',
       'ABalpaapaa|ABaraaapaa', 'MSpaaaaa', 'ABp[xaplrvd]pppaaa',
       'ABp[xaplrvd]paapap', 'ABp[xaplrvd]paaapa', 'MSaaapp',
       'MS[xaplrvd]apapa', 'ABalaaapar|ABalaaappl', 'ABprpappaa',
       'ABp[xaplrvd]paapaa', 'MS[xaplrvd]papp', 'ABalpppap|ABpraaaap',
       'MS[xaplrvd]paaaa', 'MS[xaplrvd]ppaa', 'ABp[xaplrvd]paappa',
       'ABp[xaplrvd]apppaa', 'C[xaplrvd]app', 'ABalpapaaa|ABarappaaa',
       'ABalap[xaplrvd]pap|ABp[xaplrvd]paaapp', 'MS[xaplrvd]appp',
       'MSaappa', 'ABalpppapa|ABpraaaapa', 'C[xaplrvd]pap',
       'D[xaplrvd][xaplrvd]', 'MSaaaaap', 'ABarpp[xaplrvd]app',
       'ABarpaap[xaplrvd]', 'ABalap[xaplrvd]ppp', 'ABalapaaaa|ABalappapa',
       'ABalpppppa|ABpraaappa', 'MS[xaplrvd]pppp', 'ABp[xaplrvd]papapa',
       'ABp[xaplrvd]aappa', 'ABalpaaaap|ABarapaaap', 'MS[xaplrvd]pppa',
       'ABalaaapal|ABalaaappr', 'C[xaplrvd]papa', 'ABp[xaplrvd]ppappp',
       'ABp[xaplrvd]pppapa', 'ABp[xaplrvd]papapp',
       'ABalpppppp|ABpraaappp', 'ABprpapppa', 'ABp[xaplrvd]ppapap',
       'ABp[xaplrvd]apappp', 'ABp[xaplrvd]paaaap',
       'ABalppappp|ABarappppp', 'ABaraap[xaplrvd]ap', 'C[xaplrvd]paa',
       'MS[xaplrvd]papa', 'MSpappa', 'ABalppappa|ABarappppa',
       'ABp[xaplrvd]apapaa', 'ABalppppap|ABpraaapap',
       'ABalpaappa|ABaraaappa', 'ABp[xaplrvd]paapa',
       'ABalpaappp|ABaraaappp', 'MSpaaapp', 'MS[xaplrvd]apppa',
       'ABarpapaap|ABplaaaaap', 'MSaaaaa', 'ABalpapppp|ABarapappp',
       'ABaraap[xaplrvd]a', 'ABalaaaal|ABalaapaa',
       'ABalpapapa|ABarappapa', 'ABp[xaplrvd]aapaaa', 'MSaaaaaa',
       'MSaaaapa', 'MS[xaplrvd]apaa', 'ABp[xaplrvd]ppaap',
       'ABarpapaa|ABplaaaaa', 'ABp[xaplrvd]apppa', 'ABp[xaplrvd]papaa',
       'ABarpaaaap|ABarpaaapa', 'ABalpppapp|ABpraaaapp',
       'ABaraap[xaplrvd]pa', 'C[xaplrvd]ppaa', 'MSaaaap',
       'ABalaappap|ABalppaaap', 'ABp[xaplrvd]ppaapp', 'MS[xaplrvd]paap',
       'ABp[xaplrvd]papap', 'ABp[xaplrvd]paaap', 'ABp[xaplrvd]ppappa',
       'ABarpp[xaplrvd]pp', 'MSpaaapa', 'ABalppppp|ABpraaapp',
       'ABalaaaalp|ABalaapaap', 'MSpaapaa', 'ABp[xaplrvd]ppaaa',
       'ABp[xaplrvd]apapa', 'ABalpaapp|ABaraaapp', 'ABarpappp|ABplaaapp',
       'ABp[xaplrvd]aapapa', 'ABp[xaplrvd]pppppp', 'ABaraapaaa',
       'ABp[xaplrvd]ppapa', 'ABp[xaplrvd]ppapp', 'ABplpapppp',
       'C[xaplrvd]pppp', 'C[xaplrvd]p[xaplrvd]ap', 'MS[xaplrvd]aapa',
       'ABp[xaplrvd]papaaa', 'ABp[xaplrvd]ppaaaa', 'ABaraaaaa[xaplrvd]',
       'ABarpp[xaplrvd]ap', 'ABaraappaa', 'C[xaplrvd]pa',
       'ABp[xaplrvd]apaaap', 'ABplpapppa', 'C[xaplrvd]paaa',
       'ABalap[xaplrvd]ppa|ABalaapppp|ABalapaapp', 'ABalpappap',
       'ABaraap[xaplrvd]pp', 'MS[xaplrvd]ppap', 'ABalpppaap|ABpraaaaap',
       'ABalpappa|ABarapapa', 'ABalpaaaaa|ABarapaaaa',
       'ABalpapppa|ABarapappa', 'ABaraaaaa', 'ABp[xaplrvd]pppaa',
       'C[xaplrvd]ppp', 'ABalpppaaa|ABpraaaaaa', 'ABp[xaplrvd]apaaa',
       'ABalpapap|ABarappap', 'ABalppppaa|ABpraaapaa', 'ABarpaaaa',
       'ABarapapap', 'ABalaaap[xaplrvd]', 'ABp[xaplrvd]aapapp',
       'MS[xaplrvd]paaa', 'ABprpappa', 'ABalaapap|ABalppaap',
       'ABp[xaplrvd]aapaa', 'MSpaaaap', 'MS[xaplrvd]apapp',
       'ABalaappa|ABalppaaa', 'MSaaaapp', 'ABalppapp|ABarapppp',
       'MS[xaplrvd]paa', 'ABp[xaplrvd]pppap', 'ABalaapapp|ABalppaapp',
       'MSpaaap', 'ABp[xaplrvd]ppppp', 'ABarpappa|ABplaaapa',
       'MS[xaplrvd]apap', 'ABalap[xaplrvd]pp', 'C[xaplrvd]papp',
       'MSaaapaa', 'ABp[xaplrvd]paapp', 'MS[xaplrvd]papaa', 'ABplpappp',
       'MS[xaplrvd]aapap', 'ABarpaaap', 'C[xaplrvd]pppa',
       'ABp[xaplrvd]pppppa', 'E[xaplrvd][xaplrvd]', 'C[xaplrvd]pp',
       'ABp[xaplrvd]apaaaa', 'ABp[xaplrvd]paaaa', 'MS[xaplrvd]pap',
       'ABalappaa', 'ABalaaaar', 'ABp[xaplrvd]pppaap',
       'ABalaaaar[xaplrvd]', 'Cpapa', 'ABalpaapap|ABaraaapap',
       'ABaraap[xaplrvd]p', 'ABalapaaa', 'ABalaappp|ABalapaap', 'MSpaaaa',
       'ABalappap', 'ABp[xaplrvd]aappp', 'ABalpaaaa|ABarapaaa',
       'ABalpaaap|ABarapaap', 'ABp[xaplrvd]papa', 'ABalpppaa|ABpraaaaa',
       'ABalppapap|ABarapppap', 'ABarpp[xaplrvd]aa', 'MS[xaplrvd]apa',
       'ABalpappp|ABarapapp', 'ABarpapaaa|ABplaaaaaa',
       'ABp[xaplrvd]appap', 'ABprpappp', 'ABp[xaplrvd]pppa',
       'MS[xaplrvd]pp', 'ABp[xaplrvd]aapap', 'ABalpapp|ABarapap',
       'ABp[xaplrvd]appp', 'ABp[xaplrvd]apppp', 'MS[xaplrvd]aap',
       'ABalaapp', 'ABaraaaap', 'ABalap[xaplrvd]pa', 'ABplpappaa',
       'ABalppp|ABpraaa', 'C[xaplrvd]aa', 'ABarpapp|ABplaaap',
       'MS[xaplrvd]app', 'ABalpapaa|ABarappaa', 'ABp[xaplrvd]paaa',
       'MS[xaplrvd]ppa', 'MS[xaplrvd]aaa', 'ABp[xaplrvd]ppaa',
       'ABp[xaplrvd]pppp', 'ABalpppp|ABpraaap', 'C[xaplrvd]aa[xaplrvd]',
       'ABarpp[xaplrvd]p', 'ABalaaaa', 'ABalpppa|ABpraaaa',
       'ABp[xaplrvd]apaa', 'ABalpaaa|ABarapaa', 'ABplpappa', 'ABaraaaa',
       'ABalap[xaplrvd]p', 'ABp[xaplrvd]apap', 'MS[xaplrvd]ppp',
       'ABarpapap|ABplaaaap', 'MS[xaplrvd]pa', 'ABaraap[xaplrvd]',
       'ABarpaap', 'ABp[xaplrvd]appa', 'E[xaplrvd][xaplrvd][xaplrvd]',
       'ABarpp[xaplrvd]', 'MS[xaplrvd]aa', 'ABalapaa', 'ABp[xaplrvd]ppap',
       'ABp[xaplrvd]paap', 'ABp[xaplrvd]aapa', 'ABalpapa|ABarappa',
       'ABalppap|ABarappp', 'ABp[xaplrvd]apapp', 'ABprpapp', 'ABalppaa',
       'ABalappa', 'D[xaplrvd]', 'ABp[xaplrvd]app', 'C[xaplrvd]',
       'ABalppa', 'ABarp[xaplrvd]', 'ABarpapa|ABplaaaa',
       'ABp[xaplrvd]ppa', 'C[xaplrvd]ap', 'ABp[xaplrvd]ppp', 'ABalaapa',
       'ABaraa[xaplrvd]', 'ABp[xaplrvd]aapp', 'ABa[xaplrvd][xaplrvd]',
       'ABp[xaplrvd]pap', 'ABp[xaplrvd]a[xaplrvd]', 'ABalaaap',
       'ABalpa[xaplrvd]', 'ABarpaaa', 'MS[xaplrvd]p', 'ABalpaap|ABaraaap',
       'ABalaa[xaplrvd]', 'ABp[xaplrvd]pp', 'ABp[xaplrvd]aap', 'ABarapa',
       'ABplpapp', 'ABp[xaplrvd]pa', 'MS[xaplrvd]ap', 'C[xaplrvd]a',
       'MS[xaplrvd]a', 'ABalap[xaplrvd]', 'ABarpa[xaplrvd]',
       'C[xaplrvd]p', 'ABp[xaplrvd]paa', 'ABp[xaplrvd]apa',
       'ABarpp[xaplrvd]a', 'MS[xaplrvd]'], dtype=object)

### Extract leaves for lineages

In [72]:
import dendropy

In [73]:
pruned_tree = dendropy.Tree.get(path="/workspaces/1-phydist/main/data/celegans_packer/raw/celegans_1.nwk", schema='newick')
# add taxa to internal nodes
for node in pruned_tree.internal_nodes():
  node.taxon = dendropy.Taxon(node.label)
leaf_labels = np.array([t.taxon.label for t in pruned_tree.leaf_nodes()])
leaf_labels = pd.Series(leaf_labels).sort_values()

In [74]:
leaf_labels

0      ABALAAAALAL
1      ABALAAAALAR
2      ABALAAAALPA
3      ABALAAAALPP
4      ABALAAAARLA
          ...
595       MSPPPPAP
596       MSPPPPPA
597       MSPPPPPP
666            P4A
667            P4P
Length: 668, dtype: object

In [75]:
meta_regex_lineages_joined_set

array(['MS[xaplrvd]apaap', 'D[xaplrvd][xaplrvd]p',
       'ABalpappaa|ABarapapaa', 'ABalppppa|ABpraaapa', 'ABaraaaapa',
       'ABp[xaplrvd]ppapaa', 'ABalpaapa|ABaraaapa',
       'ABalaaaala|ABalaapaaa', 'ABp[xaplrvd]paaaaa',
       'ABp[xaplrvd]ppppaa', 'ABp[xaplrvd]aapaap', 'ABp[xaplrvd]ppppap',
       'ABarpp[xaplrvd]pa', 'MS[xaplrvd]apaaa', 'ABp[xaplrvd]ppaapa',
       'MS[xaplrvd]apppp', 'ABalppapaa|ABarapppaa',
       'D[xaplrvd][xaplrvd]a', 'ABalaapppa|ABalapaapa',
       'ABp[xaplrvd]appaa', 'ABprpappap', 'ABp[xaplrvd]apaap',
       'ABalaapppp|ABalapaapp', 'ABalapaaap|ABalappapp', 'C[xaplrvd]ppa',
       'ABp[xaplrvd]ppppa', 'ABp[xaplrvd]apaaapa', 'ABalappaap',
       'ABprpapppp', 'Caapa', 'ABalapppaa', 'ABp[xaplrvd]apppap',
       'ABalppapa|ABarapppa', 'ABp[xaplrvd]paappp',
       'ABalpaapaa|ABaraaapaa', 'MSpaaaaa', 'ABp[xaplrvd]pppaaa',
       'ABp[xaplrvd]paapap', 'ABp[xaplrvd]paaapa', 'MSaaapp',
       'MS[xaplrvd]apapa', 'ABalaaapar|ABalaaappl', 'ABprpappaa',
       'ABp[xaplrvd]paapaa', 'MS[xaplrvd]papp', 'ABalpppap|ABpraaaap',
       'MS[xaplrvd]paaaa', 'MS[xaplrvd]ppaa', 'ABp[xaplrvd]paappa',
       'ABp[xaplrvd]apppaa', 'C[xaplrvd]app', 'ABalpapaaa|ABarappaaa',
       'ABalap[xaplrvd]pap|ABp[xaplrvd]paaapp', 'MS[xaplrvd]appp',
       'MSaappa', 'ABalpppapa|ABpraaaapa', 'C[xaplrvd]pap',
       'D[xaplrvd][xaplrvd]', 'MSaaaaap', 'ABarpp[xaplrvd]app',
       'ABarpaap[xaplrvd]', 'ABalap[xaplrvd]ppp', 'ABalapaaaa|ABalappapa',
       'ABalpppppa|ABpraaappa', 'MS[xaplrvd]pppp', 'ABp[xaplrvd]papapa',
       'ABp[xaplrvd]aappa', 'ABalpaaaap|ABarapaaap', 'MS[xaplrvd]pppa',
       'ABalaaapal|ABalaaappr', 'C[xaplrvd]papa', 'ABp[xaplrvd]ppappp',
       'ABp[xaplrvd]pppapa', 'ABp[xaplrvd]papapp',
       'ABalpppppp|ABpraaappp', 'ABprpapppa', 'ABp[xaplrvd]ppapap',
       'ABp[xaplrvd]apappp', 'ABp[xaplrvd]paaaap',
       'ABalppappp|ABarappppp', 'ABaraap[xaplrvd]ap', 'C[xaplrvd]paa',
       'MS[xaplrvd]papa', 'MSpappa', 'ABalppappa|ABarappppa',
       'ABp[xaplrvd]apapaa', 'ABalppppap|ABpraaapap',
       'ABalpaappa|ABaraaappa', 'ABp[xaplrvd]paapa',
       'ABalpaappp|ABaraaappp', 'MSpaaapp', 'MS[xaplrvd]apppa',
       'ABarpapaap|ABplaaaaap', 'MSaaaaa', 'ABalpapppp|ABarapappp',
       'ABaraap[xaplrvd]a', 'ABalaaaal|ABalaapaa',
       'ABalpapapa|ABarappapa', 'ABp[xaplrvd]aapaaa', 'MSaaaaaa',
       'MSaaaapa', 'MS[xaplrvd]apaa', 'ABp[xaplrvd]ppaap',
       'ABarpapaa|ABplaaaaa', 'ABp[xaplrvd]apppa', 'ABp[xaplrvd]papaa',
       'ABarpaaaap|ABarpaaapa', 'ABalpppapp|ABpraaaapp',
       'ABaraap[xaplrvd]pa', 'C[xaplrvd]ppaa', 'MSaaaap',
       'ABalaappap|ABalppaaap', 'ABp[xaplrvd]ppaapp', 'MS[xaplrvd]paap',
       'ABp[xaplrvd]papap', 'ABp[xaplrvd]paaap', 'ABp[xaplrvd]ppappa',
       'ABarpp[xaplrvd]pp', 'MSpaaapa', 'ABalppppp|ABpraaapp',
       'ABalaaaalp|ABalaapaap', 'MSpaapaa', 'ABp[xaplrvd]ppaaa',
       'ABp[xaplrvd]apapa', 'ABalpaapp|ABaraaapp', 'ABarpappp|ABplaaapp',
       'ABp[xaplrvd]aapapa', 'ABp[xaplrvd]pppppp', 'ABaraapaaa',
       'ABp[xaplrvd]ppapa', 'ABp[xaplrvd]ppapp', 'ABplpapppp',
       'C[xaplrvd]pppp', 'C[xaplrvd]p[xaplrvd]ap', 'MS[xaplrvd]aapa',
       'ABp[xaplrvd]papaaa', 'ABp[xaplrvd]ppaaaa', 'ABaraaaaa[xaplrvd]',
       'ABarpp[xaplrvd]ap', 'ABaraappaa', 'C[xaplrvd]pa',
       'ABp[xaplrvd]apaaap', 'ABplpapppa', 'C[xaplrvd]paaa',
       'ABalap[xaplrvd]ppa|ABalaapppp|ABalapaapp', 'ABalpappap',
       'ABaraap[xaplrvd]pp', 'MS[xaplrvd]ppap', 'ABalpppaap|ABpraaaaap',
       'ABalpappa|ABarapapa', 'ABalpaaaaa|ABarapaaaa',
       'ABalpapppa|ABarapappa', 'ABaraaaaa', 'ABp[xaplrvd]pppaa',
       'C[xaplrvd]ppp', 'ABalpppaaa|ABpraaaaaa', 'ABp[xaplrvd]apaaa',
       'ABalpapap|ABarappap', 'ABalppppaa|ABpraaapaa', 'ABarpaaaa',
       'ABarapapap', 'ABalaaap[xaplrvd]', 'ABp[xaplrvd]aapapp',
       'MS[xaplrvd]paaa', 'ABprpappa', 'ABalaapap|ABalppaap',
       'ABp[xaplrvd]aapaa', 'MSpaaaap', 'MS[xaplrvd]apapp',
       'ABalaappa|ABalppaaa', 'MSaaaapp', 'ABalppapp|ABarapppp',
       'MS[xaplrvd]paa', 'ABp[xaplrvd]pppap', 'ABalaapapp|ABalppaapp',
       'MSpaaap', 'ABp[xaplrvd]ppppp', 'ABarpappa|ABplaaapa',
       'MS[xaplrvd]apap', 'ABalap[xaplrvd]pp', 'C[xaplrvd]papp',
       'MSaaapaa', 'ABp[xaplrvd]paapp', 'MS[xaplrvd]papaa', 'ABplpappp',
       'MS[xaplrvd]aapap', 'ABarpaaap', 'C[xaplrvd]pppa',
       'ABp[xaplrvd]pppppa', 'E[xaplrvd][xaplrvd]', 'C[xaplrvd]pp',
       'ABp[xaplrvd]apaaaa', 'ABp[xaplrvd]paaaa', 'MS[xaplrvd]pap',
       'ABalappaa', 'ABalaaaar', 'ABp[xaplrvd]pppaap',
       'ABalaaaar[xaplrvd]', 'Cpapa', 'ABalpaapap|ABaraaapap',
       'ABaraap[xaplrvd]p', 'ABalapaaa', 'ABalaappp|ABalapaap', 'MSpaaaa',
       'ABalappap', 'ABp[xaplrvd]aappp', 'ABalpaaaa|ABarapaaa',
       'ABalpaaap|ABarapaap', 'ABp[xaplrvd]papa', 'ABalpppaa|ABpraaaaa',
       'ABalppapap|ABarapppap', 'ABarpp[xaplrvd]aa', 'MS[xaplrvd]apa',
       'ABalpappp|ABarapapp', 'ABarpapaaa|ABplaaaaaa',
       'ABp[xaplrvd]appap', 'ABprpappp', 'ABp[xaplrvd]pppa',
       'MS[xaplrvd]pp', 'ABp[xaplrvd]aapap', 'ABalpapp|ABarapap',
       'ABp[xaplrvd]appp', 'ABp[xaplrvd]apppp', 'MS[xaplrvd]aap',
       'ABalaapp', 'ABaraaaap', 'ABalap[xaplrvd]pa', 'ABplpappaa',
       'ABalppp|ABpraaa', 'C[xaplrvd]aa', 'ABarpapp|ABplaaap',
       'MS[xaplrvd]app', 'ABalpapaa|ABarappaa', 'ABp[xaplrvd]paaa',
       'MS[xaplrvd]ppa', 'MS[xaplrvd]aaa', 'ABp[xaplrvd]ppaa',
       'ABp[xaplrvd]pppp', 'ABalpppp|ABpraaap', 'C[xaplrvd]aa[xaplrvd]',
       'ABarpp[xaplrvd]p', 'ABalaaaa', 'ABalpppa|ABpraaaa',
       'ABp[xaplrvd]apaa', 'ABalpaaa|ABarapaa', 'ABplpappa', 'ABaraaaa',
       'ABalap[xaplrvd]p', 'ABp[xaplrvd]apap', 'MS[xaplrvd]ppp',
       'ABarpapap|ABplaaaap', 'MS[xaplrvd]pa', 'ABaraap[xaplrvd]',
       'ABarpaap', 'ABp[xaplrvd]appa', 'E[xaplrvd][xaplrvd][xaplrvd]',
       'ABarpp[xaplrvd]', 'MS[xaplrvd]aa', 'ABalapaa', 'ABp[xaplrvd]ppap',
       'ABp[xaplrvd]paap', 'ABp[xaplrvd]aapa', 'ABalpapa|ABarappa',
       'ABalppap|ABarappp', 'ABp[xaplrvd]apapp', 'ABprpapp', 'ABalppaa',
       'ABalappa', 'D[xaplrvd]', 'ABp[xaplrvd]app', 'C[xaplrvd]',
       'ABalppa', 'ABarp[xaplrvd]', 'ABarpapa|ABplaaaa',
       'ABp[xaplrvd]ppa', 'C[xaplrvd]ap', 'ABp[xaplrvd]ppp', 'ABalaapa',
       'ABaraa[xaplrvd]', 'ABp[xaplrvd]aapp', 'ABa[xaplrvd][xaplrvd]',
       'ABp[xaplrvd]pap', 'ABp[xaplrvd]a[xaplrvd]', 'ABalaaap',
       'ABalpa[xaplrvd]', 'ABarpaaa', 'MS[xaplrvd]p', 'ABalpaap|ABaraaap',
       'ABalaa[xaplrvd]', 'ABp[xaplrvd]pp', 'ABp[xaplrvd]aap', 'ABarapa',
       'ABplpapp', 'ABp[xaplrvd]pa', 'MS[xaplrvd]ap', 'C[xaplrvd]a',
       'MS[xaplrvd]a', 'ABalap[xaplrvd]', 'ABarpa[xaplrvd]',
       'C[xaplrvd]p', 'ABp[xaplrvd]paa', 'ABp[xaplrvd]apa',
       'ABarpp[xaplrvd]a', 'MS[xaplrvd]'], dtype=object)

In [76]:
leaf_matches = pd.DataFrame(np.zeros((len(leaf_labels), len(meta_regex_lineages_joined_set))).astype(bool))
leaf_matches.columns = meta_regex_lineages_joined_set
leaf_matches.index = leaf_labels
for rexp in tqdm(meta_regex_lineages_joined_set):
  leaf_matches[rexp] = leaf_labels.str.fullmatch(str.upper(rexp)).values
leaf_matches

100%|██████████| 304/304 [00:00<00:00, 2618.81it/s]

,MS[xaplrvd]apaap,D[xaplrvd][xaplrvd]p,ABalpappaa|ABarapapaa,ABalppppa|ABpraaapa,ABaraaaapa,ABp[xaplrvd]ppapaa,ABalpaapa|ABaraaapa,ABalaaaala|ABalaapaaa,ABp[xaplrvd]paaaaa,ABp[xaplrvd]ppppaa,...,MS[xaplrvd]ap,C[xaplrvd]a,MS[xaplrvd]a,ABalap[xaplrvd],ABarpa[xaplrvd],C[xaplrvd]p,ABp[xaplrvd]paa,ABp[xaplrvd]apa,ABarpp[xaplrvd]a,MS[xaplrvd]
ABALAAAALAL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAALAR,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAALPA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAALPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAARLA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSPPPPAP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPPPA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
P4A,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
P4P,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [77]:
meta_regex_lineages_joined_set_to_leaf = {}
matched_leaves = set()
for reg in meta_regex_lineages_joined_set:
  if leaf_matches[reg].any():
    leaf = leaf_matches.index[np.argmax(leaf_matches[reg])]
    meta_regex_lineages_joined_set_to_leaf[reg] = leaf
    matched_leaves.add(leaf)

# Log columns that will be dropped
columns_to_drop = leaf_matches.columns[leaf_matches.columns.isin(meta_regex_lineages_joined_set_to_leaf.keys())]
print("Columns to drop:", columns_to_drop.tolist())

# Log rows that will be dropped
rows_to_drop = leaf_matches.index[leaf_matches.index.isin(matched_leaves)]
print("Rows to drop:", rows_to_drop.tolist())

# drop matched columns
leaf_matches = leaf_matches[leaf_matches.columns[~leaf_matches.columns.isin(meta_regex_lineages_joined_set_to_leaf.keys())]]
# drop matched rows
leaf_matches = leaf_matches.iloc[~leaf_matches.index.isin(matched_leaves)]
leaf_matches

Columns to drop: ['ABp[xaplrvd]aapaap', 'MS[xaplrvd]paap']
Rows to drop: ['ABPLAAPAAP', 'MSAPAAP']

,MS[xaplrvd]apaap,D[xaplrvd][xaplrvd]p,ABalpappaa|ABarapapaa,ABalppppa|ABpraaapa,ABaraaaapa,ABp[xaplrvd]ppapaa,ABalpaapa|ABaraaapa,ABalaaaala|ABalaapaaa,ABp[xaplrvd]paaaaa,ABp[xaplrvd]ppppaa,...,MS[xaplrvd]ap,C[xaplrvd]a,MS[xaplrvd]a,ABalap[xaplrvd],ABarpa[xaplrvd],C[xaplrvd]p,ABp[xaplrvd]paa,ABp[xaplrvd]apa,ABarpp[xaplrvd]a,MS[xaplrvd]
ABALAAAALAL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAALAR,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAALPA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAALPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAARLA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSPPPPAP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPPPA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
P4A,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
P4P,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [78]:
len(set(meta_regex_lineages_joined_set_to_leaf.values()))

2

In [79]:
leaf_matches.any().any()  # no matches left

False

In [80]:
to_prune =  leaf_matches.index.values
pruned_tree.prune_taxa_with_labels(to_prune)
pruned_tree.update_taxon_namespace()
leaf_labels = np.array([t.taxon.label for t in pruned_tree.leaf_nodes()])
print('to_prune', len(to_prune), 'remaining', len(leaf_labels))

to_prune 666 remaining 298

In [81]:
unmatched_meta_regex = leaf_matches.columns
leaf_labels = pd.Series(leaf_labels).sort_values()
leaf_matches = pd.DataFrame(np.zeros((len(leaf_labels), len(unmatched_meta_regex))).astype(bool))
leaf_matches.columns = unmatched_meta_regex
leaf_matches.index = leaf_labels
for rexp in tqdm(unmatched_meta_regex):
  leaf_matches[rexp] = leaf_labels.str.fullmatch(str.upper(rexp)).values
leaf_matches

100%|██████████| 302/302 [00:00<00:00, 5061.01it/s]

,MS[xaplrvd]apaap,D[xaplrvd][xaplrvd]p,ABalpappaa|ABarapapaa,ABalppppa|ABpraaapa,ABaraaaapa,ABp[xaplrvd]ppapaa,ABalpaapa|ABaraaapa,ABalaaaala|ABalaapaaa,ABp[xaplrvd]paaaaa,ABp[xaplrvd]ppppaa,...,MS[xaplrvd]ap,C[xaplrvd]a,MS[xaplrvd]a,ABalap[xaplrvd],ABarpa[xaplrvd],C[xaplrvd]p,ABp[xaplrvd]paa,ABp[xaplrvd]apa,ABarpp[xaplrvd]a,MS[xaplrvd]
ABALAAAALA,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAALP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAARL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAARR,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAPAL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSPPPAA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPAP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPPA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
P4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [82]:
for reg in leaf_matches.columns:
  if leaf_matches[reg].any():
    leaf = leaf_matches.index[np.argmax(leaf_matches[reg])]
    meta_regex_lineages_joined_set_to_leaf[reg] = leaf
    matched_leaves.add(leaf)

# drop matched columns
leaf_matches = leaf_matches[leaf_matches.columns[~leaf_matches.columns.isin(meta_regex_lineages_joined_set_to_leaf.keys())]]
# drop matched rows
leaf_matches = leaf_matches.iloc[~leaf_matches.index.isin(matched_leaves)]
leaf_matches

,MS[xaplrvd]apaap,ABalpappaa|ABarapapaa,ABalppppa|ABpraaapa,ABp[xaplrvd]ppapaa,ABalpaapa|ABaraaapa,ABalaapppp|ABalapaapp,C[xaplrvd]ppa,ABp[xaplrvd]ppppa,ABp[xaplrvd]apppap,ABalppapa|ABarapppa,...,MS[xaplrvd]ap,C[xaplrvd]a,MS[xaplrvd]a,ABalap[xaplrvd],ABarpa[xaplrvd],C[xaplrvd]p,ABp[xaplrvd]paa,ABp[xaplrvd]apa,ABarpp[xaplrvd]a,MS[xaplrvd]
ABALAAAARR,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAPPL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAPPR,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAPAAA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAPAAP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSPPPAA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPAP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPPA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
P4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [83]:
len(set(meta_regex_lineages_joined_set_to_leaf.values()))

127

In [84]:
leaf_matches.any().any()  # no matches left

False

In [85]:
to_prune =  leaf_matches.index.values
pruned_tree.prune_taxa_with_labels(to_prune)
pruned_tree.update_taxon_namespace()
leaf_labels = np.array([t.taxon.label for t in pruned_tree.leaf_nodes()])
print('to_prune', len(to_prune), 'remaining', len(leaf_labels))

to_prune 171 remaining 190

In [86]:
unmatched_meta_regex = leaf_matches.columns
leaf_labels = pd.Series(leaf_labels).sort_values()
leaf_matches = pd.DataFrame(np.zeros((len(leaf_labels), len(unmatched_meta_regex))).astype(bool))
leaf_matches.columns = unmatched_meta_regex
leaf_matches.index = leaf_labels
for rexp in tqdm(unmatched_meta_regex):
  leaf_matches[rexp] = leaf_labels.str.fullmatch(str.upper(rexp)).values
leaf_matches

100%|██████████| 177/177 [00:00<00:00, 5598.86it/s]

,MS[xaplrvd]apaap,ABalpappaa|ABarapapaa,ABalppppa|ABpraaapa,ABp[xaplrvd]ppapaa,ABalpaapa|ABaraaapa,ABalaapppp|ABalapaapp,C[xaplrvd]ppa,ABp[xaplrvd]ppppa,ABp[xaplrvd]apppap,ABalppapa|ABarapppa,...,MS[xaplrvd]ap,C[xaplrvd]a,MS[xaplrvd]a,ABalap[xaplrvd],ABarpa[xaplrvd],C[xaplrvd]p,ABp[xaplrvd]paa,ABp[xaplrvd]apa,ABarpp[xaplrvd]a,MS[xaplrvd]
ABALAAAALA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAALP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAARL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAPAL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAPAR,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSPAPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPAA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPAP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [87]:
for reg in leaf_matches.columns:
  if leaf_matches[reg].any():
    leaf = leaf_matches.index[np.argmax(leaf_matches[reg])]
    meta_regex_lineages_joined_set_to_leaf[reg] = leaf
    matched_leaves.add(leaf)

# drop matched columns
leaf_matches = leaf_matches[leaf_matches.columns[~leaf_matches.columns.isin(meta_regex_lineages_joined_set_to_leaf.keys())]]
# drop matched rows
leaf_matches = leaf_matches.iloc[~leaf_matches.index.isin(matched_leaves)]
leaf_matches  # nothing left

,MS[xaplrvd]apaap,ABalpappaa|ABarapapaa,ABp[xaplrvd]ppapaa,ABalaapppp|ABalapaapp,ABp[xaplrvd]apppap,ABp[xaplrvd]paappp,ABalap[xaplrvd]pap|ABp[xaplrvd]paaapp,MSaaaaap,ABp[xaplrvd]apappp,ABalppappp|ABarappppp,...,ABp[xaplrvd]pa,MS[xaplrvd]ap,C[xaplrvd]a,MS[xaplrvd]a,ABalap[xaplrvd],ABarpa[xaplrvd],C[xaplrvd]p,ABp[xaplrvd]paa,ABp[xaplrvd]apa,MS[xaplrvd]
ABARAPAAP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABARAPPAP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABPRAAAPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
DAPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
DPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
EPL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
EPR,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [88]:
len(set(meta_regex_lineages_joined_set_to_leaf.values()))

183

In [89]:
to_prune =  leaf_matches.index.values
pruned_tree.prune_taxa_with_labels(to_prune)
pruned_tree.update_taxon_namespace()
leaf_labels = np.array([t.taxon.label for t in pruned_tree.leaf_nodes()])
print('to_prune', len(to_prune), 'remaining', len(leaf_labels))

to_prune 7 remaining 184

In [90]:
unmatched_meta_regex = leaf_matches.columns
leaf_labels = pd.Series(leaf_labels).sort_values()
leaf_matches = pd.DataFrame(np.zeros((len(leaf_labels), len(unmatched_meta_regex))).astype(bool))
leaf_matches.columns = unmatched_meta_regex
leaf_matches.index = leaf_labels
for rexp in tqdm(unmatched_meta_regex):
  leaf_matches[rexp] = leaf_labels.str.fullmatch(str.upper(rexp)).values
leaf_matches

100%|██████████| 121/121 [00:00<00:00, 4274.64it/s]

,MS[xaplrvd]apaap,ABalpappaa|ABarapapaa,ABp[xaplrvd]ppapaa,ABalaapppp|ABalapaapp,ABp[xaplrvd]apppap,ABp[xaplrvd]paappp,ABalap[xaplrvd]pap|ABp[xaplrvd]paaapp,MSaaaaap,ABp[xaplrvd]apappp,ABalppappp|ABarappppp,...,ABp[xaplrvd]pa,MS[xaplrvd]ap,C[xaplrvd]a,MS[xaplrvd]a,ABalap[xaplrvd],ABarpa[xaplrvd],C[xaplrvd]p,ABp[xaplrvd]paa,ABp[xaplrvd]apa,MS[xaplrvd]
ABALAAAALA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAALP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAARL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAPAL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAPAR,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSPAPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPAA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPAP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [91]:
for reg in leaf_matches.columns:
  if leaf_matches[reg].any():
    leaf = leaf_matches.index[np.argmax(leaf_matches[reg])]
    meta_regex_lineages_joined_set_to_leaf[reg] = leaf
    matched_leaves.add(leaf)

# drop matched columns
leaf_matches = leaf_matches[leaf_matches.columns[~leaf_matches.columns.isin(meta_regex_lineages_joined_set_to_leaf.keys())]]
# drop matched rows
leaf_matches = leaf_matches.iloc[~leaf_matches.index.isin(matched_leaves)]
leaf_matches  # nothing left

,MS[xaplrvd]apaap,ABalpappaa|ABarapapaa,ABp[xaplrvd]ppapaa,ABalaapppp|ABalapaapp,ABp[xaplrvd]apppap,ABp[xaplrvd]paappp,ABalap[xaplrvd]pap|ABp[xaplrvd]paaapp,MSaaaaap,ABp[xaplrvd]apappp,ABalppappp|ABarappppp,...,ABp[xaplrvd]pa,MS[xaplrvd]ap,C[xaplrvd]a,MS[xaplrvd]a,ABalap[xaplrvd],ABarpa[xaplrvd],C[xaplrvd]p,ABp[xaplrvd]paa,ABp[xaplrvd]apa,MS[xaplrvd]
EP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [92]:
len(set(meta_regex_lineages_joined_set_to_leaf.values()))

183

In [93]:
leaf_matches.any().any()  # no matches left

False

In [94]:
to_prune =  leaf_matches.index.values
pruned_tree.prune_taxa_with_labels(to_prune)
pruned_tree.update_taxon_namespace()
leaf_labels = np.array([t.taxon.label for t in pruned_tree.leaf_nodes()])
print('to_prune', len(to_prune), 'remaining', len(leaf_labels))

to_prune 1 remaining 183

In [95]:
unmatched_meta_regex = leaf_matches.columns
leaf_labels = pd.Series(leaf_labels).sort_values()
leaf_matches = pd.DataFrame(np.zeros((len(leaf_labels), len(unmatched_meta_regex))).astype(bool))
leaf_matches.columns = unmatched_meta_regex
leaf_matches.index = leaf_labels
for rexp in tqdm(unmatched_meta_regex):
  leaf_matches[rexp] = leaf_labels.str.fullmatch(str.upper(rexp)).values
leaf_matches

100%|██████████| 121/121 [00:00<00:00, 4999.56it/s]

,MS[xaplrvd]apaap,ABalpappaa|ABarapapaa,ABp[xaplrvd]ppapaa,ABalaapppp|ABalapaapp,ABp[xaplrvd]apppap,ABp[xaplrvd]paappp,ABalap[xaplrvd]pap|ABp[xaplrvd]paaapp,MSaaaaap,ABp[xaplrvd]apappp,ABalppappp|ABarappppp,...,ABp[xaplrvd]pa,MS[xaplrvd]ap,C[xaplrvd]a,MS[xaplrvd]a,ABalap[xaplrvd],ABarpa[xaplrvd],C[xaplrvd]p,ABp[xaplrvd]paa,ABp[xaplrvd]apa,MS[xaplrvd]
ABALAAAALA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAALP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAARL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAPAL,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ABALAAAPAR,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSPAPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPAA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPAP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPA,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MSPPPP,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [96]:
for reg in leaf_matches.columns:
  if leaf_matches[reg].any():
    leaf = leaf_matches.index[np.argmax(leaf_matches[reg])]
    meta_regex_lineages_joined_set_to_leaf[reg] = leaf
    matched_leaves.add(leaf)

# drop matched columns
leaf_matches = leaf_matches[leaf_matches.columns[~leaf_matches.columns.isin(meta_regex_lineages_joined_set_to_leaf.keys())]]
# drop matched rows
leaf_matches = leaf_matches.iloc[~leaf_matches.index.isin(matched_leaves)]
leaf_matches  # nothing left

Empty DataFrame
Columns: [MS[xaplrvd]apaap, ABalpappaa|ABarapapaa, ABp[xaplrvd]ppapaa, ABalaapppp|ABalapaapp, ABp[xaplrvd]apppap, ABp[xaplrvd]paappp, ABalap[xaplrvd]pap|ABp[xaplrvd]paaapp, MSaaaaap, ABp[xaplrvd]apappp, ABalppappp|ABarappppp, MS[xaplrvd]papa, ABalppppap|ABpraaapap, ABarpapaap|ABplaaaaap, MSaaaaa, ABaraap[xaplrvd]a, ABalpapapa|ABarappapa, ABalpppapp|ABpraaaapp, ABaraap[xaplrvd]pa, MSaaaap, ABalppppp|ABpraaapp, ABp[xaplrvd]ppaaa, ABp[xaplrvd]apapa, MS[xaplrvd]aapa, ABp[xaplrvd]ppaaaa, ABarpp[xaplrvd]ap, C[xaplrvd]pa, ABp[xaplrvd]apaaap, ABalap[xaplrvd]ppa|ABalaapppp|ABalapaapp, ABalpappa|ABarapapa, ABaraaaaa, ABarpaaaa, ABp[xaplrvd]aapapp, MS[xaplrvd]paaa, ABprpappa, ABalaapap|ABalppaap, ABp[xaplrvd]aapaa, ABalaappa|ABalppaaa, ABp[xaplrvd]pppap, MSpaaap, ABplpappp, ABarpaaap, C[xaplrvd]pp, ABp[xaplrvd]apaaaa, ABalappaa, ABalaaaar, ABp[xaplrvd]pppaap, ABalapaaa, MSpaaaa, ABp[xaplrvd]papa, MS[xaplrvd]apa, ABprpappp, ABp[xaplrvd]pppa, MS[xaplrvd]pp, ABalpapp|ABarapap, ABp[xaplrvd]appp, MS[xaplrvd]aap, ABalaapp, ABaraaaap, ABalap[xaplrvd]pa, ABalppp|ABpraaa, MS[xaplrvd]app, ABp[xaplrvd]paaa, MS[xaplrvd]aaa, ABp[xaplrvd]ppaa, ABp[xaplrvd]pppp, ABalpppp|ABpraaap, ABalaaaa, ABalpppa|ABpraaaa, ABp[xaplrvd]apaa, ABalpaaa|ABarapaa, ABplpappa, ABaraaaa, ABalap[xaplrvd]p, MS[xaplrvd]pa, ABaraap[xaplrvd], ABarpaap, ABarpp[xaplrvd], MS[xaplrvd]aa, ABalapaa, ABp[xaplrvd]ppap, ABp[xaplrvd]paap, ABp[xaplrvd]aapa, ABalpapa|ABarappa, ABalppap|ABarappp, ABp[xaplrvd]apapp, ABprpapp, ABalappa, D[xaplrvd], ABp[xaplrvd]app, C[xaplrvd], ABalppa, ABarp[xaplrvd], ABarpapa|ABplaaaa, ABp[xaplrvd]ppa, C[xaplrvd]ap, ABp[xaplrvd]ppp, ABalaapa, ABaraa[xaplrvd], ABa[xaplrvd][xaplrvd], ABp[xaplrvd]pap, ...]
Index: []

[0 rows x 121 columns]

In [97]:
len(set(meta_regex_lineages_joined_set_to_leaf.values()))

183

In [98]:
meta_regex_lineages_joined

AAACCTGAGGGCTCTC-300.1.1                            MS[xaplrvd]apaap
AAACCTGAGTTGAGTA-300.1.1                        D[xaplrvd][xaplrvd]p
AAACCTGCAAGGTTCT-300.1.1                       ABalpappaa|ABarapapaa
AAACCTGGTGTGAATA-300.1.1                         ABalppppa|ABpraaapa
AAACCTGGTTTACTCT-300.1.1                                  ABaraaaapa
                                              ...
TTTGGTTTCCCTGACT-r17        ABalap[xaplrvd]ppa|ABalaapppp|ABalapaapp
TTTGTCACATTAGGCT-r17                              ABp[xaplrvd]papapa
TTTGTCAGTCGAACAG-r17                               ABp[xaplrvd]paaap
TTTGTCATCACGCATA-r17                                 ABp[xaplrvd]aap
TTTGTCATCGCCTGAG-r17                               ABp[xaplrvd]paapa
Length: 25383, dtype: object

In [99]:
cell_to_leaf_df = pd.DataFrame(meta_regex_lineages_joined, columns=['regex_joined'])
cell_to_leaf_df.index.name = 'og_idx'
cell_to_leaf_df = cell_to_leaf_df.loc[cell_to_leaf_df['regex_joined'].isin(meta_regex_lineages_joined_set_to_leaf.keys())]
cell_to_leaf_df['leaf'] = cell_to_leaf_df['regex_joined'].replace(meta_regex_lineages_joined_set_to_leaf)
cell_to_leaf_df

                                   regex_joined        leaf
og_idx
AAACCTGAGTTGAGTA-300.1.1   D[xaplrvd][xaplrvd]p        DAAP
AAACCTGGTGTGAATA-300.1.1    ABalppppa|ABpraaapa   ABPRAAAPA
AAACCTGGTTTACTCT-300.1.1             ABaraaaapa  ABARAAAAPA
AAACCTGTCATCTGCC-300.1.1    ABalpaapa|ABaraaapa   ABARAAAPA
AAACCTGTCCAGATCA-300.1.1  ABalaaaala|ABalaapaaa  ABALAAAALA
...                                         ...         ...
TTTGGTTGTGCGATAG-r17            MS[xaplrvd]ppap     MSAPPAP
TTTGGTTTCAACACTG-r17      ABalapaaaa|ABalappapa  ABALAPAAAA
TTTGTCACATTAGGCT-r17         ABp[xaplrvd]papapa  ABPLPAPAPA
TTTGTCAGTCGAACAG-r17          ABp[xaplrvd]paaap   ABPRPAAAP
TTTGTCATCGCCTGAG-r17          ABp[xaplrvd]paapa   ABPRPAAPA

[18514 rows x 2 columns]

In [ ]:
import os
from pathlib import Path

# Create directory structure
output_base = Path('/workspaces/CellTreeBench/data/celegans_mid')
p0_dir = output_base / 'P0'
raw_dir = output_base / 'raw'

# Ensure directories exist
p0_dir.mkdir(parents=True, exist_ok=True)
raw_dir.mkdir(parents=True, exist_ok=True)

# Save tree file
tree_file_path = p0_dir / 'p0-topology_tree.nwk'
pruned_tree.write(path=str(tree_file_path), schema='newick')
print(f"Saved tree to: {tree_file_path}")

# Gene expression pre-processing

In [ ]:
# Optional: Save cell_to_leaf_df for reference (not required by dataset class)
# cell_to_leaf_file_path = raw_dir / 'c_elegans_cell_to_leaf_df.csv' 
# cell_to_leaf_df.to_csv(cell_to_leaf_file_path)
# print(f"Saved cell_to_leaf_df to: {cell_to_leaf_file_path}")

print("Skipping cell_to_leaf_df save - not required by dataset class")

In [102]:
cell_to_leaf_df

                                   regex_joined        leaf
og_idx
AAACCTGAGTTGAGTA-300.1.1   D[xaplrvd][xaplrvd]p        DAAP
AAACCTGGTGTGAATA-300.1.1    ABalppppa|ABpraaapa   ABPRAAAPA
AAACCTGGTTTACTCT-300.1.1             ABaraaaapa  ABARAAAAPA
AAACCTGTCATCTGCC-300.1.1    ABalpaapa|ABaraaapa   ABARAAAPA
AAACCTGTCCAGATCA-300.1.1  ABalaaaala|ABalaapaaa  ABALAAAALA
...                                         ...         ...
TTTGGTTGTGCGATAG-r17            MS[xaplrvd]ppap     MSAPPAP
TTTGGTTTCAACACTG-r17      ABalapaaaa|ABalappapa  ABALAPAAAA
TTTGTCACATTAGGCT-r17         ABp[xaplrvd]papapa  ABPLPAPAPA
TTTGTCAGTCGAACAG-r17          ABp[xaplrvd]paaap   ABPRPAAAP
TTTGTCATCGCCTGAG-r17          ABp[xaplrvd]paapa   ABPRPAAPA

[18514 rows x 2 columns]

In [109]:
cell_to_leaf_df['leaf'].unique().shape

(183,)

In [103]:
from scipy.io import mmread
# R sparse matrix
data_path = '/workspaces/1-phydist/main/phylodist/notebooks/17-celegans_large/raw'
expression_adata = mmread(f'{data_path}/cds_filt_exprs.mm')
print(expression_adata.shape)

# load row names
file_name = f"/workspaces/1-phydist/main/phylodist/notebooks/17-celegans_large/raw/cds_filt_cell_barcodes.csv"
barcodes_list = pd.read_csv(file_name, header=None).values.flatten()
print(len(barcodes_list))

all_gene_names = pd.read_csv(f'{data_path}/cds_filt_gene_names.csv', header=None, names=['id'])
all_gene_names = all_gene_names.id.values
print(len(all_gene_names))

expression_df = pd.DataFrame(expression_adata.toarray())
expression_df.index = barcodes_list
expression_df.columns = all_gene_names
expression_df = expression_df.loc[cell_to_leaf_df.index]
expression_df

(389755, 27138)
389755
27138

,2L52.1,rga-9,nas-6,rabr-2,sri-20,spe-10,ugt-49,AC3.5,col-151,ugt-1,...,CBG30989,CBG31085,CBG31201,CBG31218,CBG31260,CBG31272,CBG31295,CBG31521,CBG31534,CBG30842
og_idx,,,,,,,,,,,,,,,,,,,,,
AAACCTGAGTTGAGTA-300.1.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAACCTGGTGTGAATA-300.1.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAACCTGGTTTACTCT-300.1.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAACCTGTCATCTGCC-300.1.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAACCTGTCCAGATCA-300.1.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTGTGCGATAG-r17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTTGGTTTCAACACTG-r17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTTGTCACATTAGGCT-r17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTTGTCAGTCGAACAG-r17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTTGTCATCGCCTGAG-r17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Save expression data
expression_file_path = raw_dir / 'c_elegans_expression_df.csv'
expression_df.to_csv(expression_file_path)
print(f"Saved expression data to: {expression_file_path}")

In [105]:
# select rows in cell_meta as org_idx in expression_df
cell_meta = cell_meta.loc[cell_to_leaf_df.index]
cell_meta['leaf'] = cell_to_leaf_df['leaf']
cell_meta

,barcode,Size_Factor,n.umi,cell,sample.name,batch,time.point,species,suffix,sample,...,cel_lineage_broad,cbr_lineage_broad,lineage_broad,lineage_specific,cel_lineage_complete,cbr_lineage_complete,lineage_complete,germline_pseudotime,global_local_cluster,leaf
og_idx,,,,,,,,,,,,,,,,,,,,,
AAACCTGAGTTGAGTA-300.1.1,AAACCTGAGTTGAGTA-300.1.1,2.915885,4238,AAACCTGAGTTGAGTA-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,Dxxp,unassigned,Dxxp,Dxap,Dxap,unassigned,Dxap,NaN,2_25,DAAP
AAACCTGGTGTGAATA-300.1.1,AAACCTGGTGTGAATA-300.1.1,0.988692,1442,AAACCTGGTGTGAATA-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,ABalppppa/ABpraaapa,unassigned,ABalppppa/ABpraaapa,ABalppppa/ABpraaapa,ABalppppa/ABpraaapa,unassigned,ABalppppa/ABpraaapa,NaN,18_17,ABPRAAAPA
AAACCTGGTTTACTCT-300.1.1,AAACCTGGTTTACTCT-300.1.1,0.880747,1281,AAACCTGGTTTACTCT-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,ABaraaaapa,unassigned,ABaraaaapa,ABaraaaapa,ABaraaaapa,unassigned,ABaraaaapa,NaN,40_39,ABARAAAAPA
AAACCTGTCATCTGCC-300.1.1,AAACCTGTCATCTGCC-300.1.1,1.142702,1669,AAACCTGTCATCTGCC-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,ABalpaapa/ABaraaapa,unassigned,ABalpaapa/ABaraaapa,ABalpaapa/ABaraaapa,ABalpaapa/ABaraaapa,unassigned,ABalpaapa/ABaraaapa,NaN,127_81,ABARAAAPA
AAACCTGTCCAGATCA-300.1.1,AAACCTGTCCAGATCA-300.1.1,0.911687,1330,AAACCTGTCCAGATCA-300.1.1,180424_EMB_300_1,Waterston_300_minutes,300_minutes,C.elegans,300.1.1,1,...,ABalaaaala/ABalaapaaa,unassigned,ABalaaaala/ABalaapaaa,ABalaaaala/ABalaapaaa,ABalaaaala/ABalaapaaa,unassigned,ABalaaaala/ABalaapaaa,NaN,52_5,ABALAAAALA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTGTGCGATAG-r17,TTTGGTTGTGCGATAG-r17,0.686171,1001,TTTGGTTGTGCGATAG-r17,Murray_r17,Murray_r17,mixed,C.elegans,r17,38,...,MSxppap,unassigned,MSxppap,MSxppap,MSxppap,unassigned,MSxppap,NaN,41_17,MSAPPAP
TTTGGTTTCAACACTG-r17,TTTGGTTTCAACACTG-r17,0.916499,1332,TTTGGTTTCAACACTG-r17,Murray_r17,Murray_r17,mixed,C.elegans,r17,38,...,ABalapaaaa/ABalappapa,unassigned,ABalapaaaa/ABalappapa,ABalapaaaa/ABalappapa,ABalapaaaa/ABalappapa,unassigned,ABalapaaaa/ABalappapa,NaN,85_9,ABALAPAAAA
TTTGTCACATTAGGCT-r17,TTTGTCACATTAGGCT-r17,1.352404,1945,TTTGTCACATTAGGCT-r17,Murray_r17,Murray_r17,mixed,C.elegans,r17,38,...,ABpxpapapa,unassigned,ABpxpapapa,ABpxpapapa,ABpxpapapa,unassigned,ABpxpapapa,NaN,101_19,ABPLPAPAPA
TTTGTCAGTCGAACAG-r17,TTTGTCAGTCGAACAG-r17,1.857751,2696,TTTGTCAGTCGAACAG-r17,Murray_r17,Murray_r17,mixed,C.elegans,r17,38,...,ABpxpaaap,unassigned,ABpxpaaap,ABpxpaaap,ABpxpaaap,unassigned,ABpxpaaap,NaN,66_65,ABPRPAAAP
TTTGTCATCGCCTGAG-r17,TTTGTCATCGCCTGAG-r17,1.974634,2858,TTTGTCATCGCCTGAG-r17,Murray_r17,Murray_r17,mixed,C.elegans,r17,38,...,ABpxpaapa,unassigned,ABpxpaapa,ABpxpaapa,ABpxpaapa,unassigned,ABpxpaapa,NaN,18_17,ABPRPAAPA

In [ ]:
# Save cell metadata
cell_meta_file_path = raw_dir / 'c_elegans_cell_meta.csv'
cell_meta.to_csv(cell_meta_file_path)
print(f"Saved cell metadata to: {cell_meta_file_path}")

In [ ]:
# Summary of generated files
print("=" * 60)
print("PREPROCESSING COMPLETE!")
print("=" * 60)
print("Generated files for celegans_mid dataset:")
print()
print(f"1. Tree file: {tree_file_path}")
print(f"2. Expression data: {expression_file_path}")
print(f"3. Cell metadata: {cell_meta_file_path}")
print()
print("These files are now ready for use with CElegansDatasetBase class.")
print("=" * 60)